version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hoge0220removekey"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b2ke18r5t3j"
s3_prefix = "hoge0220removekey"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
