version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hoge0220createkey"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b2ke18r5t3j"
s3_prefix = "hoge0220createkey"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
